#version 430 core

#define R3   1.732050807	// square root of 3
#define HR3  0.866025404	// half square root of 3
#define IR3  0.577350269 	// the inverse of the square root of 3
#define HIR3 0.288675134	// half the inverse of the square root of 3


const vec2 s = vec2(1, 1.7320508);

layout (local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

layout(std430, binding = 0) buffer HexagonIds
{
    int hex_ids[];
};

layout(std140, binding = 1) uniform CanvasUniform
{
    vec2 resolution;
    vec2 board_size;
};

layout(rgba32f, binding = 2) uniform image2D imgOutput;

mat3 circlesLookUp[] = {
        //center  radius
    mat3(
        -0.5, -HIR3, HIR3,
        0.0, IR3, HIR3,
        0.5, -HIR3, HIR3
    ),
    mat3(
        -0.5, HIR3, HIR3,
        0.0, -IR3, HIR3,
        0.5, HIR3, HIR3
    ),
    mat3(
        -0.5, HR3, 1.5*IR3,
        -1., 0, 1.5*IR3,
        0.5, -HIR3, HIR3
    ),
    mat3(
        -0.5, HR3, 1.5*IR3,
        0.5, HR3, 1.5*IR3,
        0, -IR3, HIR3
    ),
    mat3(
        1.0, 0.0, 1.5*IR3,
        0.5, HR3, 1.5*IR3,
        -0.5, -HIR3, HIR3
    ),
    mat3(
        1.0, 0.0, 1.5*IR3,
        0.5, -HR3, 1.5*IR3,
        -0.5, IR3*0.5, HIR3
    ),
    mat3(
        -0.5, -HR3, 1.5*IR3,
        0.5, -HR3, 1.5*IR3,
        0., IR3, HIR3
    ),
    mat3(
        -0.5, -HR3, 1.5*IR3,
        -1.0, 0., 1.5*IR3,
        0.5, IR3 * 0.5, HIR3
    )
};

mat3x4 mixLookUp[] = {
    mat3x4(
        -0.5, 0, 0.5, 0,
        0.0, -IR3 , HIR3, 0,
        0.0, IR3, HIR3, 0
    ),
    mat3x4(
        0.25, IR3 * 0.75, -0.25, -IR3 * 0.75,
        -0.5, HIR3 , HIR3, 0,
        0.5, -HIR3, HIR3, 0
    ),  
    mat3x4(
        -0.25, IR3 * 0.75, 0.25, -IR3 * 0.75,
        0.5, HIR3 , HIR3, 0,
        -0.5, -HIR3, HIR3, 0
    ),  
    mat3x4(
        -0.5, 0., 0.5, 0.,
        -1., 0., 1.5 * IR3, 0,
        1., 0., 1.5 * IR3, 0
    ),
    mat3x4(
        -0.25, IR3 * 0.75, 0.25, -IR3 * 0.75,
        0.5, -HR3, 1.5 * IR3, 0,
        -0.5, HR3, 1.5 * IR3, 0
    ),
    mat3x4(
        0.25, IR3 * 0.75, -0.25, -IR3 * 0.75,
        -0.5, -HR3, 1.5 * IR3, 0,
        0.5, HR3, 1.5 * IR3, 0
    ),
};

float hash21(vec2 p)
{
    return fract(sin(dot(p, vec2(141.13, 289.97)))*43758.5453);
}

vec2 circle(float l, float d, float w, float r) {
    w*=10;
    float x = 0.;
    float y = step(abs(l - d), w);// * abs((l - d + w) / (2. * w) - r);
    y = (l - d + w) * 0.5/w * step(abs(l - d), w);
    //y = step(y, 10.01);
    
    return vec2(x, y);
}

float line(vec2 p1, vec2 p2, vec2 u) {
    float a = p1.y-p2.y;
    float b = p2.x-p1.x;
    return abs(a*u.x+b*u.y+p1.x*p2.y-p2.x*p1.y) / sqrt(a*a+b*b);
}

float hex(in vec2 p)
{    
    p = abs(p);

    return max(dot(p, s*.5), p.x);   
}

vec4 getHex(vec2 p)
{    
    vec4 hC = floor(vec4(p, p - vec2(.5, 1))/s.xyxy) + .5;
    
    vec4 h = vec4(p - hC.xy*s, p - (hC.zw + .5)*s);

    return dot(h.xy, h.xy) < dot(h.zw, h.zw) 
        ? vec4(h.xy, hC.xy) 
        : vec4(h.zw, hC.zw + .5);
}

void main() {
    vec2 u = vec2(0);
    
    u.y = gl_GlobalInvocationID.y / 800.;
    u.x = (gl_GlobalInvocationID.x - 50.)/800.;
    vec2 len = vec2((0.5 * board_size.y * R3 + HR3), (board_size.x + 0.5));
    vec2 uv = u;
    
    vec2 uv1 = u * len.x;
    uv1.x-=0.5;
    uv1.y-=1.73*0.5;
    
    vec2 uv2 = u * len.y;
    uv2.x-=0.5;
    uv2.y-=1.73*0.5;
    float diff = 0.;
    if(dot(uv1, vec2(0., 1.)) < dot(uv2, vec2(0., 1.))) {
        diff = len.y - len.x;
        u = uv2;
        u.y-=0.5*diff;
    } else {
        diff = len.x - len.y;
        u = uv1;
        u.x-=0.5*diff;
    }
    float offset = mod(board_size.y + 1, 2);
    u.y += HR3 * offset;
    vec4 h = getHex(u);
    
    float eDist = hex(h.xy); 


    vec3 col = vec3(0);
    h.z = floor(h.z);
    h.w *= 2.0;
    h.w = -1.*(h.w - board_size.y + 1);
    h.w += offset;
    float w = 0.01;
    float r = 1., c = 0.;
    if(h.z >= 0. && h.w >= 0. && h.z < board_size.x && h.w < board_size.y) {
        
        int id = hex_ids[int(h.w * board_size.x + h.z)];
        
        if((id & 0x3) == 0) {
            mat3 cell = circlesLookUp[id >> 2];
            c += circle(length(h.xy-vec2(cell[0][0], cell[0][1])), cell[0][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[1][0], cell[1][1])), cell[1][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[2][0], cell[2][1])), cell[2][2], w, r).y;
        } else if ((id & 0x3) == 1) {
            mat3x4 cell = mixLookUp[id >> 2];
            c = step(line(vec2(cell[0][0], cell[0][1]), vec2(cell[0][2], cell[0][3]), h.xy), w);
            c += circle(length(h.xy-vec2(cell[1][0], cell[1][1])), cell[1][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[2][0], cell[2][1])), cell[2][2], w, r).y;
        } else {
            c += step(line(vec2(0.25, IR3 * 0.75), vec2(-0.25, -IR3 * 0.75), h.xy), w);  
            c += step(line(vec2(-0.25, IR3 * 0.75), vec2(0.25, -IR3 * 0.75), h.xy), w);  
            c += step(line(vec2(-0.5, 0.), vec2(0.5, 0.), h.xy), w);   
        }
        //col = mix(vec3(0.), vec3(1), smoothstep(0., .03, eDist - .5 + .04));    
        col += vec3(c);
    } else {
        //col = mix(vec3(0.), vec3(1), smoothstep(0., .03, eDist - .5 + .04));    
        mat3 cell = circlesLookUp[0];
        if(h.w == -1. && h.z < board_size.x) {
            c += circle(length(h.xy-vec2(cell[0][0], cell[0][1])), cell[0][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[2][0], cell[2][1])), cell[2][2], w, r).y;
        }
        if(h.z == board_size.x) {
            c += circle(length(h.xy-vec2(cell[0][0], cell[0][1])), cell[0][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[1][0], cell[1][1])), cell[1][2], w, r).y;
        }
        if(h.w == board_size.y) {
            c += circle(length(h.xy-vec2(cell[1][0], cell[1][1])), cell[1][2], w, r).y;
        }
        if(h.z == -1) {
            c += circle(length(h.xy-vec2(cell[0][0], cell[0][1])), cell[0][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[1][0], cell[1][1])), cell[1][2], w, r).y;
            c += circle(length(h.xy-vec2(cell[2][0], cell[2][1])), cell[2][2], w, r).y;
        }
        //c = circle(length(h.xy-vec2(cell[0][0], cell[0][1])), cell[0][2], w, r).y;
        col += vec3(c, 0, 0);
    }
    
    if(abs(uv.x - 1.) < 0.005 || abs(uv.x) < 0.005) {
        col = vec3(0.3, 0.4, 0.5);
    } 
    imageStore(imgOutput, ivec2(gl_GlobalInvocationID.xy), vec4(col, 1));
}